INSERT INTO "beer"("name", "description", "image_url")
 VALUES
('Asahi Super Dry', 'Asahi Super Dry is with a crown cap closure by Asahi Breweries.', 'https://winevybe.com/wp-content/uploads/Asahi-Breweries-Asahi-Super-Dry.png'),
('Blue Moon Belgian White', 'Blue Moon Belgian White is with a crown cap closure by Blue Moon Brewing.', 'https://winevybe.com/wp-content/uploads/Blue-Moon-Brewing-Blue-Moon-Belgian-White.png'),
('Corona Extra', 'Extra is a beer with a crown cap closure by Corona.', 'https://winevybe.com/wp-content/uploads/Cerveceria-Modelo-Corona-Extra.png'),
('Heineken Lager', 'Lager Beer can is a beer with a can closure by Heineken.', 'https://winevybe.com/wp-content/uploads/Heineken-Heineken-can.png'),
('Bryggeri Kesaloma', 'Bryggeri Kesäloma is with a crown cap closure by Bryggeri Helsinki.', 'https://winevybe.com/wp-content/uploads/Bryggeri-Helsinki-Bryggeri-Kesaloma.png'),
('Nomada La Manchurita', 'Nomada La Manchurita is a beer with a crown cap closure by Nomada Brewing.', 'https://winevybe.com/wp-content/uploads/Nomada-Brewing-Nomada-La-Manchurita.png'),
('Hoegaarden Witbier', 'Hoegaarden Witbier is a beer with a crown cap closure by InBev', 'https://winevybe.com/wp-content/uploads/InBev-Hoegaarden-Witbier.png'),
('Kasteel Donker', 'Kasteel Donker is with a crown cap closure by Brouwerij Van Honsebrouck.', 'https://winevybe.com/wp-content/uploads/Brouwerij-Van-Honsebrouck-Kasteel-Donker.png'),
('Mustan Virran Pistolekors Porter', 'Mustan Virran Pistolekors Porter is a beer with a crown cap closure by Mustan Virran Panimo.', 'https://winevybe.com/wp-content/uploads/Mustan-Virran-Panimo-Mustan-Virran-Pistolekors-Porter.png'),
('Amager Talents & Legends Brewski', 'Amager Talents & Legends Brewski is with a crown cap closure by Amager Bryghus', 'https://winevybe.com/wp-content/uploads/Amager-Bryghus-Amager-Talents-Legends-Brewski.png'),
('Bock''s IPA', 'Bock''s IPA is with a crown cap closure by Bock''s Corner Brewery.', 'https://winevybe.com/wp-content/uploads/Bocks-Corner-Brewery-Bocks-IPA.png'),
('Aldersbacher Ursprung Export Hell', 'Aldersbacher Ursprung Export Hell is with a crown cap closure by Aldersbacher.', 'https://winevybe.com/wp-content/uploads/Aldersbacher-Aldersbacher-Ursprung-Export-Hell.png'),
('Hipster Squirrel', 'Hipster Squirrel can is a beer with a can closure by Uiltje.', 'https://winevybe.com/wp-content/uploads/Uiltje-Brewing-Co-Uiltje-Hipster-Squirrel-can.png'),
('Ruosniemen Arkkitehti Black IPA', 'Ruosniemen Arkkitehti Black IPA is a beer with a crown cap closure by Ruosniemen Panimo.', 'https://winevybe.com/wp-content/uploads/Ruosniemen-Panimo-Ruosniemen-Arkkitehti-Black-IPA.png'),
('Young''s Double Chocolate Stout', 'Young''s Double Chocolate Stout is a beer with a crown cap closure by Young''s.', 'https://winevybe.com/wp-content/uploads/Youngs-Youngs-Double-Chocolate-Stout.png'),
('Mallaskoski Jeriko Wild Ale', 'Mallaskoski Jeriko Wild Ale is a beer with a crown cap closure by Mallaskosken panimo.', 'https://winevybe.com/wp-content/uploads/Mallaskosken-panimo-Mallaskoski-Jeriko-Wild-Ale.png'),
('Sticke Altbier', 'Sticke Altbier is a beer with a lightning closure closure by Uerige.', 'https://winevybe.com/wp-content/uploads/Uerige-Obergarige-Hausbrauerei-Uerige-Sticke-Altbier.png'),
('Belgisch Speciaalbier', 'Amager Demon Juice Hazy IPA is with a crown cap closure by Amager Bryghus.', 'https://winevybe.com/wp-content/uploads/Amager-Bryghus-Amager-Demon-Juice-Hazy-IPA.png'),
('Hiisi Iku-Turso Imperial Stout', 'Hiisi Iku-Turso Imperial Stout is a beer with a crown cap closure by Panimoyhtio Hiisi.', 'https://winevybe.com/wp-content/uploads/Panimoyhtio-Hiisi-Hiisi-Iku-Turso-Imperial-Stout.png'),
('Dunkel', 'Dunkel can is a beer with a can closure by Erdinger.', 'https://winevybe.com/wp-content/uploads/Erdinger-Erdinger-Dunkel-can.pngBock''s Ruis'),
('Anderson Jean Ginie', 'Anderson Jean Ginie is with a crown cap closure by Anderson Beer OU.', 'https://winevybe.com/wp-content/uploads/Anderson-Beer-OU-Anderson-Jean-Ginie.png'),
('Arctic Pale Ale', 'Arctic Pale Ale is a beer with a crown cap closure by Tornion.', 'https://winevybe.com/wp-content/uploads/Tornion-Panimo-Tornion-Arctic-Pale-Ale.png'),
('Pikantus', 'Pikantus is a beer with a crown cap closure by Erdinger.', 'https://winevybe.com/wp-content/uploads/Erdinger-Erdinger-Pikantus.png'),
('Hefeweissbier Dunkel', 'Hefeweissbier Dunkel is a beer with a crown cap closure by Weihenstephaner.', 'https://winevybe.com/wp-content/uploads/Weihenstephan-Weihenstephaner-Hefeweissbier-Dunkel.png'),
('Thornbridge Bliss Point APA', 'Thornbridge Bliss Point APA can is a beer with a can closure by Thornbridge.', 'https://winevybe.com/wp-content/uploads/Thornbridge-Thornbridge-Bliss-Point-APA-can.png'),
('Delirium Black Barrel Aged', 'Delirium Black Barrel Aged is with a natural cork closure by Brouwerij L. Huyghe.', 'https://winevybe.com/wp-content/uploads/Brouwerij-L.-Huyghe-Delirium-Black-Barrel-Aged.png'),
('Espressway Cold Brew Coffee Stout', 'Espressway Cold Brew Coffee Stout is a beer with a crown cap closure by Two Roads.', 'https://winevybe.com/wp-content/uploads/Two-Roads-Brewing-Co-Two-Roads-Espressway-Cold-Brew-Coffee-Stout.png'),
('Pyynikin Black IPA', 'Pyynikin Black IPA is a beer with a crown cap closure by Pyynikin.', 'https://winevybe.com/wp-content/uploads/Pyynikin-Kasityolaispanimo-Pyynikin-Black-IPA.png'),
('Lil'' Crispy Ale', 'Lil'' Crispy Ale can is a beer with a metal screw cap closure by Clown Shoes.', 'https://winevybe.com/wp-content/uploads/Clown-Shoes-Clown-Shoes-Lil-Crispy-Ale-can.png'),
('Peroni Nastro Azzurro', 'Peroni Nastro Azzurro is with a crown cap closure by Birra Peroni.', 'https://winevybe.com/wp-content/uploads/Birra-Peroni-Peroni-Nastro-Azzurro.png'),
('Tsingtao Premium Lager', 'Premium Lager is a beer with a crown cap closure by Tsingtao.', 'https://winevybe.com/wp-content/uploads/Tsingtao-Brewery-Tsingtao-Premium-Lager.png'),
('Lumi Chef''s Breakfast Oatmeal Stout', 'Lumi Chef''s Breakfast Oatmeal Stout can is a beer with a can closure by Lumi Brewing.', 'https://winevybe.com/wp-content/uploads/Lumi-Brewing-Lumi-Chefs-Breakfast-Oatmeal-Stout-can.png'),
('Ballast Point Fathom', 'Ballast Point Fathom IPA is a beer with a crown cap closure by Ballast Point Brewing.', 'https://winevybe.com/wp-content/uploads/Ballast-Point-Brewing-Ballast-Point-Fathom-IPA.png'),
('Baladin Rock ''n'' Roll', 'Baladin Rock ''n'' Roll is with a crown cap closure by Baladin.', 'https://winevybe.com/wp-content/uploads/Baladin-Baladin-Rock-n-Roll.png'),
('Karhu Vehnaolut', 'Karhu Vehnaolut can is a beer with a can closure by Sinebrychoff.', 'https://winevybe.com/wp-content/uploads/Sinebrychoff-Karhu-Vehnaolut-can.png'),
('Karjala', 'Karjala can is a beer with a can closure by Hartwall.', 'https://winevybe.com/wp-content/uploads/Hartwall-Karjala-can.png'),
('Pearl Hart', 'Amager Pearl Hart is with a natural cork closure by Amager Bryghus.', 'https://winevybe.com/wp-content/uploads/Amager-Bryghus-Amager-Pearl-Hart.png'),
('Satzuma Gluten', 'Satzuma Gluten Free Session IPA is a beer with a crown cap closure by Thornbridge.', 'https://winevybe.com/wp-content/uploads/Thornbridge-Thornbridge-Satzuma-Gluten-Free-Session-IPA.png'),
('Orbital Tilt IPA', 'Captain Lawrence Orbital Tilt IPA can is with a can closure by Captain Lawrence Brewing Company.', 'https://winevybe.com/wp-content/uploads/Captain-Lawrence-Brewing-Company-Captain-Lawrence-Orbital-Tilt-IPA-can.png'),
('Delirium Red', 'Huyghe Delirium Red is with a crown cap closure by Brouwerij L. Huyghe.', 'https://winevybe.com/wp-content/uploads/Brouwerij-L.-Huyghe-Huyghe-Delirium-Red.png'),
('Hobgoblin IPA', 'Hobgoblin IPA is a beer with a crown cap closure by Wychwood.', 'https://winevybe.com/wp-content/uploads/Wychwood-Wychwood-Hobgoblin-IPA.png'),
('Draught Stout', 'Draught Stout can is a beer with a can closure by Guinness', 'https://winevybe.com/wp-content/uploads/Guinness-Guinness-Draught-Stout-can.png'),
('Jamestown New England IPA', 'Jamestown New England IPA can is a beer with a can closure by Thornbridge.', 'https://winevybe.com/wp-content/uploads/Thornbridge-Thornbridge-Jamestown-New-England-IPA-can.png'),
('Mita Humalan Jalkeen', 'Hiisi Mita Humalan Jalkeen Sour Ale is a beer with a crown cap closure by Panimoyhtio Hiisi.', 'https://winevybe.com/wp-content/uploads/Panimoyhtio-Hiisi-Hiisi-Mita-Humalan-Jalkeen-Sour-Ale.png'),
('Traquair 50 Anniversary Ale', 'Traquair 50 Anniversary Ale is a beer with a crown cap closure by Traquair Brewery.', 'https://winevybe.com/wp-content/uploads/Traquair-Brewery-Traquair-50-Anniversary-Ale.png'),
('Kipling South Pacific', 'Kipling South Pacific Pale Ale is a beer with a crown cap closure by Thornbridge.', 'https://winevybe.com/wp-content/uploads/Thornbridge-Thornbridge-Kipling-South-Pacific-Pale-Ale.png'),
('Koff Escape Route Pale Ale', 'Koff Escape Route Pale Ale can is a beer with a can closure by Sinebrychoff.', 'https://winevybe.com/wp-content/uploads/Sinebrychoff-Koff-Escape-Route-Pale-Ale-can.png'),
('Delirium Red', 'Huyghe Delirium Red is with a crown cap closure by Brouwerij L. Huyghe.', 'https://winevybe.com/wp-content/uploads/Brouwerij-L.-Huyghe-Huyghe-Delirium-Red.png'),
('Hard Decision Bourbon Barrel Aged', 'Hard Decision Bourbon Barrel Aged is a beer with a crown cap closure by La Pirata.', 'https://winevybe.com/wp-content/uploads/Cerveses-La-Pirata-La-Pirata-Hard-Decision-Bourbon-Barrel-Aged.png'),
('Prykmestar Savu', 'Prykmestar Savu is a beer with a crown cap closure by Vakka Suomen.', 'https://winevybe.com/wp-content/uploads/Vakka-Suomen-Panimo-Prykmestar-Savu.png'),
('Hummingbird', 'Hummingbird can is a beer with a can closure by Fourpure.', 'https://winevybe.com/wp-content/uploads/Fourpure-Fourpure-Hummingbird-can.png'),
('De Leckere Pilsener', 'Pilsener is a beer with a crown cap closure by De Leckere.', 'https://winevybe.com/wp-content/uploads/De-Leckere-De-Leckere-Pilsener.png'),
('Aldersbacher Aldersbacher Kloster Dunkel', 'Aldersbacher Kloster Dunkel is with a crown cap closure by Aldersbacher.', 'https://winevybe.com/wp-content/uploads/Aldersbacher-Aldersbacher-Kloster-Dunkel.png')
